name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:      
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 3.1.301
     - name: Install dependencies
       run: dotnet restore

     - name: Build
       run: dotnet build --configuration Release --no-restore
     - name: Test
       run: dotnet test --no-restore --verbosity normal
     - name: Dotnet Publish
       run: dotnet publish Starkit -c Release -o deploy
        
     - name: Update Project
       uses: garygrossgarten/github-action-ssh@release
       with: 
        command: |
          export PATH="$PATH:$HOME/.dotnet/tools/"
          cd /var/www/starkit/Starkit
          git pull origin master
          dotnet ef database update
          rm -R bin
          rm -R obj
          sudo systemctl stop starkit.service
          dotnet restore
          dotnet build
          dotnet publish
          sudo systemctl daemon-reload
          sudo systemctl restart starkit.service
          sudo nginx -s reload
          sudo chown -R www-data:www-data /var/www
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
